// Bug happens on JVM 
// WITH_RUNTIME
// WITH_COROUTINES
// TARGET_BACKEND: JVM
// FILE: I.kt

                          interface I {
    fun antb(): String {
    var uudi = ""
class MyException(message: String): Exception("")
val obj = "" as java.lang.Object

    synchronized (obj) {
        {
            var uudi = "qdktj"
            equals(-4940821718597795629L)
toString()
val obj = "" as java.lang.Object
        }
equals(-1390231183416357290L)
equals(164016292)
equals(-7442923529496033259L)
synchronized (obj) {
            equals(-2048390677622306934L)
equals(1364354190)
equals(188651296)
equals(1431535705)
equals(1868047347)
equals(5766397509932246237L)
obj.wait(1)
        equals(-631136008262773209L)
fun wgxp(n: Number) {
    {val obj = obj; ""}
{
  operator fun Int.component1() = 164016292
  toString()
operator fun Int.component2() = 1364354190
1868047347.component2()
}
if (!n.equals(n)) throw Error("fail 1 for $n")
    equals(268105106)
@file:[JvmName("") JvmMultifileClass]
if (n.equals(1)) throw Error("fail 2 for $n")
    n.equals(-631136008262773209L)
n.equals(4940821718597795629L)
n.equals(-7442923529496033259L)
n.equals(794545189)
n.equals(7442923529496033259L)
n.equals(1390231183416357290L)
("fail 2 for $n")
"fail 1 for $n"
foo@ n
if (n.equals(1L)) throw Error("fail 3 for $n")
    n.equals(-492389026)
if (n != n) throw Error("fail 4 for $n")
    do {
        n.equals(5422062020099807185L)
operator fun Int.component2() = 1364354190

        if (n != n) throw Error("ydoyn")
        var uudi = "ctkdw"

        foo@ n.equals(7442923529496033259L)
n.toString()
n.equals(-2048390677622306934L)
foo@ n.equals(631136008262773209L)
foo@ n.equals(-6909395313011280486L)
794545189
        if (n != n) throw Error("ydoyn")
    1364354190.component2()
} while (n.equals(-631136008262773209L))
equals(164016292)
"fail 2 for $n"
(n)
arrayListOf(-8337617179569595360, -6193126639661598631, 8213459669693659118) != listOf(3801605843677013065, 5492302536935025458, 3081523915839116931, -7981391636282517935)
if (false) throw Error("fail 1 for $n")
foo@ n.equals(-7981391636282517935)
631136008262773209L as Long?
(n).equals(-7442923529496033259L)
if (n == 1) throw Error("fail 5 for $n")
    (n).equals(-631136008262773209L)
operator fun Int.component2() = 1364354190
if (n != n) throw Error("ydoyn")
"" == "fail 2 for $n"
(n).equals(-6193126639661598631)
if (n == 1L) throw Error("fail 6 for $n")
    n.equals(7981391636282517935)
(n).equals(2048390677622306934L)
while (equals(7462339015715978255)) if (n.equals(1)) throw Error("fail 2 for $n")
164016292.component2()
foo@ n.equals(3801605843677013065)
AssertionError("fail 4 for $n")
n.equals(8153990113575397455L)
(n).equals(n)
n.equals(3081523915839116931)
do {
            n.equals(631136008262773209L)
1364354190.component2().component2()
(n).toString()
n
            { "fail 2 for $n" }
foo@ n.equals(2187929256101990603L)
if ("" == "fail 2 for $n") throw Error("fail 2 for $n")
        } while (equals(1))
if (equals(5217112305080682784)) throw Error("ffkxh")
492389026.component2()
if (n.equals(1L)) throw Error("fail 3 for $n")
while (n.equals(n)) if (n.equals(1)) throw Error("fail 2 for $n")
if (n.hashCode() != n.toInt()) throw Error("fail 7 for $n")
    foo@ n.equals(5201977301636737505L)
n.equals(6707282445740733383L)
(n).toString()
(n).equals(1364354190.component2())
!equals(hashCode())
if (n.toString() != "$n") throw Error("fail 8 for $n")
throw Error("hzezc")
}
}
    equals(-7104490863398762682)
var qwsv = 0
var dyni = 1
}

    if (equals(hashCode())) throw Error("pgmnb")
return "OK"
}
suspend fun foo(x: Int): String
}




// FILE: JavaClass.java

public class JavaClass implements I {
    @Override
    public Object foo(int x, kotlin.coroutines.Continuation<? super String> continuation) {
        continuation.resumeWith("OK");
        return kotlin.coroutines.intrinsics.IntrinsicsKt.getCOROUTINE_SUSPENDED();
    }
}
// FILE: main.kt



fun <T> result(): Byte = (null)!!

fun box(): String {
    
val s = false
if (s) {val name: (HashMap<suspend () -> Unit, List<Int>>)?} else "O"


    
val y = true
try
{arrayOf("hmnke")}
catch(e: Exception){}
finally{}


val w = false
when (w) {
 false -> {do {
              


val name: Float?
          } while (true)}
 else -> {do {
              


val charList = mutableListOf<Char>()
          } while (false)}
}


val o = true
try
{{ x, y, z -> "$x-$y-$z" }}
catch(e: Exception){}
finally{}


val x = false
if (x) throw AssertionError("Should be executed once") else {null is (Exception)?}




val q = true
if (q) {
    lateinit var ok: String
    run {
        ok = "OK"
    }
    return ok
} else {ArrayList<(Float)?>()}


    do do {
        
val d = false
try
{val name: (Map<CharSequence,Int>)?}
catch(e: Exception){}
finally{}

        

val r = true
try
{1208943552}
catch(e: Exception){}
finally{}

        
val j = false
try
{do {
        562923670.unaryMinus()
    }
          while(true)}
catch(e: Exception){}
finally{}

    
val w = false
try
{arrayOf({
              
val name: Short=10705.unaryMinus()
          
}, "ipsil")!!.get(909935363)}
catch(e: Exception){

}
finally{}

}
          while(false) while (false)

val f = false
when (f) {
 true -> {do "vlxgf" as (Array<Set<Byte>>)? as (Float)?
          while(false)}
 else -> {do "vlxgf" as Exception as String
          while(false)}
}

null is String


do "abcdef"
          while(false)


val r = false
if (r) {do { val name: (Exception)? } while (null is Exception)} else {do { val name: (UInt)? } while (null is UInt)}


val g = true
try
{{
              
val name: Char
          
}}
catch(e: Exception){}
finally{}


val c = false
try
{"OK"}
catch(e: Exception){}
finally{}


val b = true
if (b) {{
              
val name: String="wgrji"
          
}} else {{
              
val name: (Set<Byte>)?
          
}}

return "baz"

}
