// Bug happens on JVM 
// FILE: tmp0.kt


fun check()  =
try {
{if (true) 
::withVarargs
}
} catch(e: Exception){}

